browserName=chrome
#browserName=edge

osName=Windows

#Should use below variable if running in local
ENV=staging

objectTimeout=60
timeSleep=1000

# STAGING =========================================================================================

staging.baseUrl=https://qa-assignment.oivan.vn
staging.mailInboxUrl=https://qa-assignment.oivan.vn/letter_opener


# Demo account
staging.username=Dr.LeeannaConnHuels@oivan.com
staging.password=12345678
